name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [composer, npm]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Environment Variables
        run: |
          REPOSITORY_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPOSITORY_NAME=$(echo "${{ github.repository }}" | awk -F'/' '{print $2}' | tr '[:upper:]' '[:lower:]')
          BRANCH_NAME=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}' | tr '[:upper:]' '[:lower:]')
          echo "REPOSITORY_OWNER=${REPOSITORY_OWNER}" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=${REPOSITORY_NAME}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "APP_IMAGE=ghcr.io/${REPOSITORY_OWNER}/${REPOSITORY_NAME}:${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="ghcr.io/${APP_IMAGE}-${{ github.sha }}"
          docker build --build-arg ENV_FILE=.env -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          docker tag $IMAGE_NAME "ghcr.io/${APP_IMAGE}"
          docker push "ghcr.io/${APP_IMAGE}"